const FIELD_LABEL_MAP = {
  query_ta_dividend_apiUri: '接口地址',
  query_ta_dividend_paged: '是否分页',
  query_ta_dividend_queryConditions: '查询条件',
  query_ta_dividend_pageConditions: '分页参数',
  query_ta_dividend_fields: '出参字段',
  query_ta_dividend_pageResults: '分页返回字段',
  query_ta_dividend_total_size: '总记录数',
  query_ta_dividend_total_page_num: '总页数',
  query_ta_dividend_page_size: '每页条数',
  query_ta_dividend_curr_page: '当前页',
  query_ta_dividend_curr_page_size: '当前页记录数',
  query_ta_dividend_list: '数据列表',
  query_ta_dividend_taaccountid: '投资人基金帐号',
  query_ta_dividend_confirmdate: '确认日期',
  query_ta_dividend_fundcode: '基金代码',
  query_ta_dividend_sharetype: '份额类型',
  query_ta_dividend_distributorcode: '销售人代码',
  query_ta_dividend_branchcode: '网点号码',
  query_ta_dividend_basisforcalculatingdividend: '分红的份额基数',
  query_ta_dividend_dividendorshare: '红利/红股标志',
  query_ta_dividend_volofdividedforreinvestment: '红股份数（再投资份额）',
  query_ta_dividend_dividendamount: '红利总金额',
  query_ta_dividend_commission: '手续费(再投资费用)',
  query_ta_dividend_stampduty: '印花税（业绩报酬）',
  query_ta_dividend_dividendindeed: '实发红利金额',
  query_ta_dividend_currencytype: '结算币种',
  query_ta_dividend_registrationdate: '权益登记日期',
  query_ta_dividend_dividentdate: '分红发放日',
  query_ta_dividend_lastdate: '再投资发放日',
  query_ta_dividend_tradeacco: '交易账号',
  query_ta_dividend_frozenshares: '冻结份额',
  query_ta_dividend_frozenbalance: '冻结金额',
  query_ta_dividend_netvalue: '再投资单位净值',
  query_ta_dividend_cserialno: 'TA确认编号',
  query_ta_dividend_unitprofit2: '每单位基金分红金额',
  query_ta_dividend_reinvestbalance: '再投资金额',
  query_ta_dividend_dividend: '中登模式TA分红业绩报酬',
  query_ta_dividend_memo: '备注',
  query_ta_dividend_manager_name: '管理人名字',
  query_ta_dividend_manager_no: '管理人代码',
  query_ta_dividend_investorname: '投资者名称',
  query_ta_dividend_agencyname: '销售商名称',
  query_ta_dividend_fundname: '产品名称',
  query_ta_dividend_bgcfmdate: '开始日期',
  query_ta_dividend_endcfmdate: '结束日期',
  query_ta_dividend_interface_code: '接口编码'
}

export function getFieldLabel(tradeName, fieldName) {
  if (!fieldName) return '--'
  return FIELD_LABEL_MAP[`${tradeName}_${fieldName}`] || '--'
}
